services:
  nostr-rs-relay:
    image: scsibug/nostr-rs-relay:latest
    user: root:root
    ports:
      - 7000:7000
    volumes:
      - ./.nostr/config.toml:/usr/src/app/config.toml
      - ./.nostr/data:/usr/src/app/db


networks:
  relay:
  