services:
  orangecheckr:
    build: ./proxy
    container_name: orangecheckr
    network_mode: host
    restart: always
    env_file: ./proxy/.env
    stop_signal: SIGTERM
  redis:
    command: redis-server --save 60 1 --maxmemory-policy noeviction

networks:
  relay:
