services:
  nostr-rs-relay:
    image: scsibug/nostr-rs-relay:latest
    container_name: relay
    user: root:root
    ports:
      - 7000:8080
    restart: always
    volumes:
      - ./.nostr/config.toml:/usr/src/app/config.toml
      - ./.nostr/data:/usr/src/app/db
  redis:
    image: redis
    container_name: redis
    command: redis-server --save 60 1 --loglevel debug --maxmemory-policy noeviction
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./.nostr/redis:/data

networks:
  relay:
